In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import numpy as np

# Array Creation

In [2]:
# creatning a simple array

arr1=np.array([10,20,30,40,50])
print(arr1)


[10 20 30 40 50]


In [3]:
# creating a 2d array

arr2=np.array([[1,2,3,4],[4,5,6,7],[7,8,9,1]])
print(arr2)

[[1 2 3 4]
 [4 5 6 7]
 [7 8 9 1]]


In [4]:
# creating a 3d array

arr3=np.array([[[1,2,3],[4,5,6]],[[3,2,1],[4,5,6]],[[6,4,2],[7,2,6]]])
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[3 2 1]
  [4 5 6]]

 [[6 4 2]
  [7 2 6]]]


# Basic Methods

In [ ]:
# arange()

print(np.arange(1,10))
print(np.arange(1,10,2))

In [ ]:
# reshape()

print(arr2)
print("After reshaping the array")
print(arr2.reshape(2,6))  #2 row and 6 column
print("\n\n")

# reshape of 3d array

print(arr3)
print("After reshaping the 3d array")
print(arr3.reshape(2,3,3))  # 2-> two 2d array, 3,3-> 3 row & 3 column

In [ ]:
# np.ones and np.zeros

arr_zero=np.zeros((3,5))  # creating 3 * 5 matrix with 0 values only 
print(arr_zero,"\n")

arr_ones= np.ones((3,4))  # creating 3 * 4 matrix with 1 values only
print(arr_ones)

In [ ]:
#np.random

arr_random_values=np.random.random((3,3))   # creating 3*3 matrix with random values
print(arr_random_values)

In [ ]:
# np.linspace

print(np.linspace(1,15,6))
print(np.linspace(1,15,6,dtype=int))   # creating 6 values between 1 to 5 with equal distance

In [ ]:
#np.identity

print(np.identity(4))  #printing 4*4 identity matrix

In [ ]:
#np.full

np.full((2,3),18)  # creating 2*3 matrix with 18 values only
np.full((2,2,2),18)  # creating 2*2*2 tensor/3d array with 18 values only

# Array Attributes

In [ ]:
# ndim

print(arr1)
print(arr1.ndim) # printing the dimention of the array
print("---------------------")
print(arr2)
print(arr2.ndim)
print("---------------------")
print(arr3)
print(arr3.ndim)

In [4]:
# dtype

arr1=np.array([2,1,3,4],dtype=float)
print(arr1)
print(arr1.dtype)

[2. 1. 3. 4.]
float64


In [ ]:
# shape 

print(arr1)
print(arr1.shape) # printing the shape of the array
print("---------------------")
print(arr2)
print(arr2.shape)
print("---------------------")
print(arr3)
print(arr3.shape)

In [ ]:
# size

print(arr1.size)  #printing total number of element in array
print(arr2.size)
print(arr3.size)

In [ ]:
# itemsize

print(arr1.itemsize)  # printing the size of each element in array
print(arr2.itemsize)

In [ ]:
# dtype 

print(arr1.dtype)  # printing the data type of each element in array

In [ ]:
# changing the data type of array

print(arr1)
print(arr1.dtype)
print("-------------")
print(arr1.astype(float))
print(arr1.astype(np.int32))

In [ ]:
# Array Operations

a=np.arange(10)
b=np.arange(10)

In [ ]:
# scalar operations 

print(a)
print(a+2)
print(a-2)
print(a*2)

In [ ]:
# relational oprations

print(b<5)
print(a==b)

In [ ]:
# vector operations

print(a+b)
a-b
a*b
a**b

# Array Functions

In [8]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
# max/min/sum/prod
# 0 -> col and 1 -> row

print(np.max(a,axis=0))
print(np.min(a,axis=1))
print(np.sum(a))
print(np.prod(a,axis=1))


[6 7 8]
[0 3 6]
36
[  0  60 336]


In [17]:
# mean/median/std/var

print(np.mean(a))
print(np.median(a,axis=0))

4.0
[3. 4. 5.]


In [18]:
# trigonomoetric functions

np.sin(a)

array([[ 0.        ,  0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825]])

In [ ]:
# Dot Production

x=np.arange(6).reshape(2,3)
y=np.arange(6).reshape(3,2)
print(x)
print(y)

print(np.dot(x,y))

# note 1st matrix column == 2nd matrix row count in this (2,3)&(3,2)

[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]
[[10 13]
 [28 40]]


In [ ]:
# round/floor/ceil

print(np.round([3.5,3.4]))  # if .5 or more then next number as normal we do
print(np.floor([3.5,3.4]))  # it will take only intiger value like 3.4 = 3
print(np.ceil([3.5,3.4]))   # if 3.4, 3.2 ,3.5 ,3.6 then it take 4 for all

[4. 3.]
[3. 3.]
[4. 4.]


# Array Indexing and Slicing

In [ ]:
a1=np.arange(12).reshape(3,4)
a1

In [ ]:
# Indexcing

a1[[0,2],[0,3]]  # Fancy indexing ## it gives (0,0) element and (2,3)
a3[(0,0,2,2),(0,0,1,1),(0,2,0,2)]  # fancy 3D indexing

In [ ]:
# Sclicing

a1[::2,::3]

In [ ]:
a1[::2,1::2]

In [ ]:
a1[1,::3]

In [ ]:
a1[0:2,1:]

In [ ]:
a3=np.arange(27).reshape(3,3,3)
a3

In [ ]:
a3[1]

In [ ]:
a3[::2]

In [ ]:
a3[0,1,:]

In [ ]:
a3[1,:,1]

In [ ]:
a3[2,1:,1:]

In [ ]:
a3[::2,0,::2]

# Iterating

In [ ]:
print(arr1)

for i in arr1: # printing 1d array one by one
    print(i)

[10 20 30 40 50]
10
20
30
40
50


In [7]:
print(arr2)

for i in arr2: # printing 2d array row by row
    print(i)

[[1 2 3 4]
 [4 5 6 7]
 [7 8 9 1]]
[1 2 3 4]
[4 5 6 7]
[7 8 9 1]


In [ ]:
print(arr3)
print()

for i in arr3: # for loop consider each 2D array as one iteration sor in arr3 3 iteration
    print(i)

[[[1 2 3]
  [4 5 6]]

 [[3 2 1]
  [4 5 6]]

 [[6 4 2]
  [7 2 6]]]

[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [4 5 6]]
[[6 4 2]
 [7 2 6]]


# Reshaping

In [10]:
# reshape()

reshaping_demo=np.arange(12).reshape(4,3)
print(reshaping_demo)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [11]:
# transpose

print(np.transpose(reshaping_demo)) # it convert row into column and column into row

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [ ]:
# ravel

print(np.ravel(reshaping_demo))  # it convert 2d and 3d array into 1d array
print(reshaping_demo.ravel())   # another way to use ravel()

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


# Stacking

In [16]:
# horizontal stacking

a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [22]:
print(np.hstack((a4,a5)),"\n")
print(np.hstack((a4,a5,a4,np.arange(9).reshape(3,3))))

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]] 

[[ 0  1  2  3 12 13 14 15  0  1  2  3  0  1  2]
 [ 4  5  6  7 16 17 18 19  4  5  6  7  3  4  5]
 [ 8  9 10 11 20 21 22 23  8  9 10 11  6  7  8]]


In [23]:
# vertical stacking

print(np.vstack((a5,a4)))

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# Splitting

In [28]:
# horizotal split

print(a5)
print(np.hsplit(a5,2)) # it will split horizontaly in 2 parts

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[array([[12, 13],
       [16, 17],
       [20, 21]]), array([[14, 15],
       [18, 19],
       [22, 23]])]


In [ ]:
# vertical split

print(np.vsplit(a5,3))  # array split verticaly in 3 part

[array([[12, 13, 14, 15]]), array([[16, 17, 18, 19]]), array([[20, 21, 22, 23]])]
